name = "GraphQLParser"
uuid = "0ae10fbf-af58-4883-b66b-ff0ac82d20dd"
authors = ["Mal Miller and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
