name = "GraphQLParser"
uuid = "0ae10fbf-af58-4883-b66b-ff0ac82d20dd"
authors = ["Mal Miller and contributors"]
version = "0.1.0"

[deps]
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"

[compat]
Parsers = "2.1.2"
julia = "1"